### ISSUE TITLE
Sending integers to Python RPC is not possible?

### ISSUE THREAD

**Issue by vegabook** [esl/Pyrlang#13]
Sending integers to Python RPC does not seem to work. Is that on purpose? Must I serialize non-strings? Examples below from Elixir. 
```

tbrowne@cubietruck ~/c/e/p/p/p/Pyrlang> iex --sname erl --cookie COOKIE
Erlang/OTP 20 [erts-9.1] [source] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.5.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(erl@localhost)1> :rpc.call(:'py@localhost', :'test2', :'printit2', ['1', '2'])
:undefined
iex(erl@localhost)2> :rpc.call(:'py@localhost', :'test2', :'printit2', [1, 2])    
{:badrpc,
 {:EXIT,
  {{:AttributeError,
    %{args: {'\'str\' object has no attribute \'elements_\''},
      traceback: 'Traceback (most recent call last):\n  File "/home/tbrowne/code/elix/pyrr/priv/python/Pyrlang/Pyrlang/rex.py", line 62, in handle_one_inbox_message\n    args = gencall.get_args()\n  File "/home/tbrowne/code/elix/pyrr/priv/python/Pyrlang/Pyrlang/gen.py", line 72, in get_args\n    return self.args_.elements_\nAttributeError: \'str\' object has no attribute \'elements_\'\n'}},
   {:gen_server, :call,
    [{:rex, :py@localhost}, {:call, :test2, :printit2, [1, 2], #PID<0.60.0>},
     :infinity]}}}}
iex(erl@localhost)3> 
```
Herewith the Python side:

```
tbrowne@cubietruck ~/c/e/p/p/p/Pyrlang> python3 test2.py
Dist: Listening for dist connections on port 35315
EPMD: Connecting 127.0.0.1:4369
EPMD: Socket connected
EPMD: sending ALIVE2 req ('py@localhost', 77, (5, 5))
EPMD: Connected successfully (creation 3)
send -> (atom'erl@localhost', atom'shell'): hello
Node._send_remote shell <- hello
Node: connect to node erl@localhost
Dist-out: Send_name b'n\x05\x05\x00\x03\x0f\xbcpy@localhost'
Connection to ('127.0.0.1', 35985) established
Node: wait for 'node_connected'
Out-connection established with erl@localhost
Node: connected
MonitorP: org Pid<3.95.0>@erl@localhost targ rex = <Rex at 0xb650e030>
send -> rex: (atom'$gen_call', (Pid<3.95.0>@erl@localhost, Ref<3,50579,3058171905,2856406562>@erl@localhost), (atom'call', atom'test2', atom'printit2', ['1', '2'], Pid<3.60.0>@erl@localhost))
1
2
send -> Pid<3.95.0>@erl@localhost: (Ref<3,50579,3058171905,2856406562>@erl@localhost, None)
Node._send_remote Pid<3.95.0>@erl@localhost <- (Ref<3,50579,3058171905,2856406562>@erl@localhost, None)
MonitorP: org Pid<3.95.0>@erl@localhost targ rex = <Rex at 0xb650e030>
send -> rex: (atom'$gen_call', (Pid<3.95.0>@erl@localhost, Ref<3,50619,3058171905,2856406562>@erl@localhost), (atom'call', atom'test2', atom'printit2', '\x01\x02', Pid<3.60.0>@erl@localhost))
```

and here is test2.py

```
import gevent
from gevent import monkey
monkey.patch_all()

import Pyrlang
from Pyrlang import Atom


def addit(x, y):
    return(x + y)


def printit(x):
    print(x)

def printit2(x, y):
    print(x)
    print(y)


def main():
    node = Pyrlang.Node("py@localhost", "COOKIE")
    node.start()

    pid = node.register_new_process(None)
    node.send(pid, (Atom('erl@localhost'), Atom('shell')), Atom('hello'))


    while True:
        gevent.sleep(0.5)


if __name__ == "__main__":
    main()
```

**Comment by kvakvs** [comment]
It is possible even more it supports very large integers just fine. This bug seems to related to python-side list implementation. I implemented it first to support full Erlang feature set such as strings and improper lists (where tail is not NIL []) but now I am thinking this was an overkill and simple Python lists would suffice.

**Comment by OvermindDL1** [comment]
I'd keep them as just python lists with an improper list being a subclass of list so it can be distinguished easily.

**Comment by kvakvs** [comment]
Version 0.2 uploaded.
The error here happened because of uncertainty whether Python list is used or Term.List wrapper, this has been simplified. Now erlang lists always arrive as lists not as funny objects. See http://pyrlang.readthedocs.io/en/latest/data_types.html
