### ISSUE TITLE
Does not work under Windows due to dependency on term / tty

### ISSUE THREAD

**Issue by vegabook** [esl/Pyrlang#15]
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\thoma> e:
PS E:\> cd code
PS E:\code> cd bbg
PS E:\code\bbg> ls


    Directory: E:\code\bbg


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/15/2017   8:36 AM                Pyrlang
------       10/18/2017   3:48 PM           1127 bbsubout.py
------       10/18/2017   3:48 PM          44814 z3.pkl
------       10/30/2017  10:20 AM           3299 bbcl.py
------       10/18/2017   3:48 PM            560 bbkex.py
------       10/18/2017   3:48 PM          82436 z.pkl
------       10/18/2017   3:48 PM            914 eltest.py
------       10/18/2017   3:48 PM            839 bbsub.py
------       10/18/2017   3:48 PM            923 bbpub.py
------       10/18/2017   3:47 PM             22 README.md
------       12/19/2017   1:00 PM          32099 xxnode.py
------       12/19/2017  11:34 AM          31744 bbnode.py
------       12/19/2017  12:40 PM           6059 bbmaster.py


PS E:\code\bbg> cd Pyrlang
PS E:\code\bbg\Pyrlang> python test1.py
Traceback (most recent call last):
  File "test1.py", line 5, in <module>
    import Pyrlang
  File "E:\code\bbg\Pyrlang\Pyrlang\__init__.py", line 15, in <module>
    from Pyrlang.node import *
  File "E:\code\bbg\Pyrlang\Pyrlang\node.py", line 24, in <module>
    from Pyrlang.term import *
  File "E:\code\bbg\Pyrlang\Pyrlang\term.py", line 26, in <module>
    from Pyrlang.Dist import util
  File "E:\code\bbg\Pyrlang\Pyrlang\Dist\__init__.py", line 15, in <module>
    from Pyrlang.Dist.distribution import ErlangDistribution
  File "E:\code\bbg\Pyrlang\Pyrlang\Dist\distribution.py", line 27, in <module>
    from Pyrlang.Dist.out_connection import OutConnection
  File "E:\code\bbg\Pyrlang\Pyrlang\Dist\out_connection.py", line 25, in <module>
    from Pyrlang.Dist.base_connection import *
  File "E:\code\bbg\Pyrlang\Pyrlang\Dist\base_connection.py", line 25, in <module>
    from Pyrlang import logger, mailbox, term
ImportError: cannot import name 'term'
PS E:\code\bbg\Pyrlang>
PS E:\code\bbg\Pyrlang>
PS E:\code\bbg\Pyrlang> python
Python 3.4.5 |Anaconda custom (64-bit)| (default, Jul  5 2016, 14:53:07) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import term
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\term\__init__.py", line 9, in <module>
    from termios import *
ImportError: No module named 'termios'
>>>

```

As you will see from [this google search](https://www.google.co.uk/search?client=ubuntu&hs=CVe&channel=fs&dcr=0&ei=7j06Wu7yM8f5UIvjidgH&q=windows+termios+python&oq=windows+termios+python&gs_l=psy-ab.3..0i22i30k1.4817.5463.0.5621.7.4.0.2.2.0.62.233.4.4.0....0...1c.1.64.psy-ab..1.6.239....0.uwePHMzn7hk), termios is Linux/Unix only. 

Personally I am wishing to create a Windows-domain Erlang node because the Bloomberg terminal, from which I subscribe to data, only supports Windows for the Desktop licence. So my use case is Erlang node in Python talks to Bloomberg, and transmits data to Linux side.

**Comment by vegabook** [comment]
The above error does not occur on Python 3.6 under Windows, so I am closing this issue.
